version: '3'

services:
  laravel-backend:
    build:
      context: ./product-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./product-backend:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db  
      DB_PORT: 5432
      DB_DATABASE: product-db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nextjs-frontend:
    build:
      context: ./product-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./product-frontend:/usr/src/app
    environment:
      - NODE_ENV=production

  db:
    image: postgres:latest
    container_name: my-postgres-container
    restart: always
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis-container
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: my-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel-backend

volumes:
  postgres_data:
