version: '3.8'

services:
    app:
        build:
            context: ../product-backend
            dockerfile: Dockerfile
        image: ermin99/product:v1
        container_name: laravel_app
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=product-db
            - DB_USERNAME=postgres
            - DB_PASSWORD=root
        depends_on:
            - db
        networks:
            - productnetwork

    db:
        image: postgres:latest
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=product-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - productnetwork

volumes:
    db_data:

networks:
    productnetwork:
        driver: bridge
