version: '3.8'

services:
    app:
        build:
            context: ../../product-backend
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=product-db
            - DB_USERNAME=postgres
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgres_db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=product-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
