import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/User/UserContext";
import { ProductProvider } from "./context/Product/ProductContext";
import Sidebar from "../../src/components/Sidebar/Sidebar";
import { Box, Toolbar } from "@mui/material";
import { ChatProvider } from "./context/Chat/ChatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChatProvider>
      <ProductProvider>
        <UserProvider>
          <html lang="en">
            <body className={inter.className}>
              <Sidebar />
              <Box
                component="main"
                sx={{
                  flexGrow: 1,
                  p: 3,
                  width: { sm: `calc(100% - 240px)` },
                  marginLeft: "240px",
                }}
              >
                <Toolbar />
                {children}
              </Box>
            </body>
          </html>
        </UserProvider>
      </ProductProvider>
    </ChatProvider>
  );
}
