name: Product app

on:
  push:
    branches:
      - master
      - deployment

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile CSS and JS
        run: |
          npm install
          npm run build
        working-directory: ./product-backend

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@master
        with:
          php-veresion: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml